example_dashboard:
    path: /example/
    controller: Webbamboo\MaterialDashboard\Controller\ExampleController::dashboard

example_profile:
    path: /example/profile/
    controller: Webbamboo\MaterialDashboard\Controller\ExampleController::profile