theme: jekyll-theme-midnight
title: Dashboard bundle for Symfony
description: The bundle is based on Creative Tim's Material Dashboard and is intended to make the integration into Symfony projects easier
show_downloads: true
plugins:
  - jekyll-admin
